### PR TITLE
Add provision for Postgres

### PR DESCRIPTION
**Pull request by neelxie**
#### What does this PR do?

This PR adds a provision to create a PostgreSQL database, it also makes provision for viewing of the said databases.
#### Ticket

https://trello.com/c/kX4C16CF
#### Screenshot
Screenshot from 2021-05-03 10-49-28
Screenshot from 2021-05-03 10-50-29
Screenshot from 2021-05-03 11-00-13

### CODE REVIEW

**Review by MutegekiHenry — APPROVED** [review]
Great work @neelxie

**Comment by kawerewagaba** [comment]
Screenshot 2021-05-06 at 19 24 57
can't seem to see the type for `mysql`

**Review by kawerewagaba — CHANGES_REQUESTED** [review]
what could be the reason i'm not able to see `mysql` in the type field. db creation works well tho.

**Comment by neelxie** [comment]
> what could be the reason i'm not able to see `mysql` in the type field. db creation works well tho.

@kawerewagaba this is because previous databases did not have provision for a database flavour and it was added at the making provision for Postgres that is why all databases created before the adding the Postgres provision do not and can not show the database flavor.

**Comment by kawerewagaba** [comment]
> > what could be the reason i'm not able to see `mysql` in the type field. db creation works well tho.
> 
> @kawerewagaba this is because previous databases did not have provision for a database flavour and it was added at the making provision for Postgres that is why all databases created before the adding the Postgres provision do not and can not show the database flavor.

makes sense

**Review by kawerewagaba — APPROVED** [review]

**Pull request merged**
