### PR TITLE
feat: redesign user activities/logs page, add new filter section and pagination

### PR DESCRIPTION
**Pull request by rhodinemma**
# Description

- Gave the user activity/logs page a better user experience by modifying the previous filter section and making it more user friendly
- Added pagination to the user's activities

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Trello Ticket ID

https://trello.com/c/Hy98uzvR

## How Can This Been Tested?

- Run this branch locally and checkout the `http://localhost:3000/activity` and logs will be fetched for that logged in user.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots

image

### CODE REVIEW

**Review by khalifan-kfan — COMMENTED** [review]
Thanks @rhodinemma 
Screenshot 2023-12-20 at 14 25 18
just a small UI issue

**Comment by rhodinemma** [comment]
> Thanks @rhodinemma Screenshot 2023-12-20 at 14 25 18 just a small UI issue

ohh, i think i missed that, let me rectify that.

**Review by neelxie — APPROVED** [review]
LGTM

**Review by mosesmulumba — APPROVED** [review]
ACK

**Pull request merged**
