### PR TITLE
Ft validate create project form

### PR DESCRIPTION
**Pull request by MutegekiHenry**
### What does this PR do?
It validates form fields of the create project form and also enfources the rule of project name should start with a letter

### How should it be tested?
Run the branch loaclly and try to create a project with empty fields "save for description field" or project name starting with anything that is not a letter

### Screenshots 

1. This shows validation of Cluster field
validate cluster name

2. This shows validation of Project Name field
validate project field

3. The rest show validation of project name format to start with a letter
i) when a number starts
prjectname wih number

ii) when any other sysmbol starts 
project name with underscore

### CODE REVIEW

**Comment by Mubangizi** [comment]
Great work @MutegekiHenry, Am sorry to say this but i dont like that green dot on the `description`, if it is badly needed, look for a way to make it fit with the rest of the form components. it looks like an outsider to me. maybe highlight the input border `green` or `red`

**Comment by StephenAraka** [comment]
> Great work @MutegekiHenry, Am sorry to say this but i dont like that green dot on the `description`, if it is badly needed, look for a way to make it fit with the rest of the form components. it looks like an outsider to me. maybe highlight the input border `green` or `red`.
> I know i ran into conclusions here, lets start afresh, what is its use?

The green dot is not part of his work... It's coming from a browser extension called `Grammarly`. Just ignore it.

**Comment by MutegekiHenry** [comment]
@neelxie @StephenAraka @Mubangizi I have worked on the feed-back you gave about the project name having only lettters and a hyphen kindly review.

#### Screenshot
Screenshot from 2020-04-08 22-03-06

**Comment by Mubangizi** [comment]
Hey @MutegekiHenry  validation works fine, though i am wondering, about `Project Name` shouldn't i be in position to add an integer on the project name some thing like `West-fork2`.
Then my other query is @MutegekiHenry i think you might have forgotten `Feedback` for successful project creation. or that is being not part of whats being handled?

**Comment by MutegekiHenry** [comment]
> Hey @MutegekiHenry validation works fine, though i am wondering, about `Project Name` shouldn't i be in position to add an integer on the project name some thing like `West-fork2`.
> Then my other query is @MutegekiHenry i think you might have forgotten `Feedback` for successful project creation. or that is being not part of whats being handled?

@Mubangizi based on the feedback i recieved from the team, we were to only allow characters and a hyphen, so as for the numbers we may have to retable it to the team and see what they say. then the success feedback is handled in another PR thats also up for review [here](https://github.com/crane-cloud/frontend/pull/118)

**Comment by MutegekiHenry** [comment]
> > Hey @MutegekiHenry validation works fine, though i am wondering, about `Project Name` shouldn't i be in position to add an integer on the project name some thing like `West-fork2`.
> > Then my other query is @MutegekiHenry i think you might have forgotten `Feedback` for successful project creation. or that is being not part of whats being handled?
> 
> @Mubangizi based on the feedback i received from the team, we were to only allow characters and a hyphen, so as for the numbers we may have to retable it to the team and see what they say. then the success feedback is handled in another PR that's also up for review [here](https://github.com/crane-cloud/frontend/pull/118)

@Mubangizi so I put this up for discussion and it was concluded that project names remain with the current implementation. But the App name with have numbers in an upcoming PR

**Pull request merged**
