### PR TITLE
Admin user profile page 

### PR DESCRIPTION
**Pull request by mirembe-mariam**
# Description
Update admin user profile page with the designs.
Apps count and databases created are static

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Trello Ticket ID
https://trello.com/c/xRsyeFXq/1660-implement-the-new-designs-for-user-details-on-the-admin-side

## How Can This Been Tested?
Login as an admin head to /accounts/<user_id>

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots
Screenshot from 2023-08-23 15-44-18

### CODE REVIEW

**Comment by khalifan-kfan** [comment]
@mirembe-mariam , Your branch has some unfinished tests that are making it fail on deployments.

**Comment by mirembe-mariam** [comment]
> @mirembe-mariam , Your branch has some unfinished tests that are making it fail on deployments. -- Run test locally and make sure they pass before pushing, the instructions to run tests are in the readme. --

Its now fine

**Review by rhodinemma — DISMISSED** [review]
Good work on this @mirembe-mariam

**Comment by khalifan-kfan** [comment]
Thanks for this @mirembe-mariam , Could you as well make the user row clickable to go to the user's profile

**Review by khalifan-kfan — APPROVED** [review]

**Review by rhodinemma — APPROVED** [review]

**Pull request merged**
