### PR TITLE
Fix context menu arrangement order

### PR DESCRIPTION
**Pull request by neelxie**
#### PR do?
Re-arrange the order for context menu items for the app card and project card.

#### Screenshots:
Before:
image

After:
image

### CODE REVIEW

**Comment by neelxie** [comment]
> Would you please do this for projects as well?

@StephenAraka I did, kindly check the changed files please.

**Comment by StephenAraka** [comment]
> > Would you please do this for projects as well?
> 
> @StephenAraka I did, kindly check the changed files please.

Alright, let me check.

**Comment by StephenAraka** [comment]
> > > Would you please do this for projects as well?
> > 
> > 
> > @StephenAraka I did, kindly check the changed files please.
> 
> Alright, let me check.
`

**Comment by StephenAraka** [comment]
> > > Would you please do this for projects as well?
> > 
> > 
> > @StephenAraka I did, kindly check the changed files please.
> 
> Alright, let me check.

Sorry, I'd closed the PR by mistake...
Seen the change @neelxie . Good job!

**Pull request merged**
