### PR TITLE
Project organisations

### PR DESCRIPTION
**Pull request by neelxie**
# Description
Preset project organisation types

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Trello Ticket ID

https://trello.com/c/lejE04Mt
## How Can This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test scenario/configuration

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots
Screenshot from 2023-06-29 09-48-34

### CODE REVIEW

**Review by rhodinemma — COMMENTED** [review]
Thanks for the implementation, but won't we need that dropdown on the registration page as well?
image

**Comment by neelxie** [comment]
> Thanks for the implementation, but won't we need that dropdown on the registration page as well? image

No. @rhodinemma  From our initial conversation we decided that you can enter your organization at Sign up -- the actual organization, for example, USAID -- while you choose organization type at project creation, which caters for the fact that a person can move from USAID and go work for UNICEF but the USAID project will never become a UNICEF project, that is why we have a provision changing user organization later, and also the provision of assigning credits based on users under a specific organization as you know credits are user assigned and not project assigned.
I hope this helps to answer your query.

**Comment by rhodinemma** [comment]
> > Thanks for the implementation, but won't we need that dropdown on the registration page as well? image
> 
> No. @rhodinemma From our initial conversation we decided that you can enter your organization at Sign up -- the actual organization, for example, USAID -- while you choose organization type at project creation, which caters for the fact that a person can move from USAID and go work for UNICEF but the USAID project will never become a UNICEF project, that is why we have a provision changing user organization later, and also the provision of assigning credits based on users under a specific organization as you know credits are user assigned and not project assigned. I hope this helps to answer your query.

Understood

**Review by rhodinemma — APPROVED** [review]
Thank you for this implementation @neelxie

**Pull request merged**
