### PR TITLE
Feature Add project description

### PR DESCRIPTION
**Pull request by neelxie**
#### What does this PR do?

Add project description 

#### Description of Task to be completed?
- Add description input to project form
- Remove alias from backend data

#### How should this be manually tested?

* Check it out here.

#### Screenshots

image

 > The description on the project

image

### CODE REVIEW

**Comment by MutegekiHenry** [comment]
> This is good work... @neelxie
> I just have a suggestion though. Since the project description is surely expected to be lengthy, we could have that input for description looking like a `textarea` (or you could in fact use a text area instead of an input)...
> 
> If need be, Please reach out to @ckwagaba concerning whether this makes sense in relation to design.
> 
> Otherwise, @Mubangizi and @MutegekiHenry ... what do you guys think of this?

I think @StephenAraka z point is valid

**Comment by neelxie** [comment]
> This is good work... @neelxie
> I just have a suggestion though. Since the project description is surely expected to be lengthy, we could have that input for description looking like a `textarea` (or you could in fact use a text area instead of an input)...
> 
> If need be, Please reach out to @ckwagaba concerning whether this makes sense in relation to design.
> 
> Otherwise, @Mubangizi and @MutegekiHenry ... what do you guys think of this?

@StephenAraka kindly do check this out it has been implemented

**Comment by neelxie** [comment]
> > This is good work... @neelxie
> > I just have a suggestion though. Since the project description is surely expected to be lengthy, we could have that input for description looking like a `textarea` (or you could in fact use a text area instead of an input)...
> > If need be, Please reach out to @ckwagaba concerning whether this makes sense in relation to design.
> > Otherwise, @Mubangizi and @MutegekiHenry ... what do you guys think of this?
> 
> I think @StephenAraka z point is valid

@MutegekiHenry I have taken the idea and implemented it.

**Comment by Mubangizi** [comment]
Hey @neelxie  good stuff, while your at that, try adding some padding to the `Cluster Dropdown` List,  it looks vague, someone might think its not supposed to be there.

**Comment by StephenAraka** [comment]
> @MutegekiHenry I have taken the idea and implemented it.

This is good.

**Comment by neelxie** [comment]
> Hey @neelxie good stuff, while your at that, try adding some padding to the `Cluster Dropdown` List, it looks vague, someone might think its not supposed to be there.

@Mubangizi Thank you for the feedback, do not that your feedback has nothing to do with my functionality for this particular pull request, but your feedback has been taken and I have created a ticket to work on it here https://trello.com/c/u77EN6cT

**Comment by neelxie** [comment]
> > @MutegekiHenry I have taken the idea and implemented it.
> 
> @neelxie ... This is good. Just add the padding that @Mubangizi suggested.
> Screenshot from 2020-04-06 10-25-02
> 
> This dropdown could use some styling... Padding + A custom hover color... Currently its the default blue.
> 
> Maybe you'll do this is a different PR? Considering this one is about Project description?

@StephenAraka thank you for the feedback and I have a ticket to handle that in a different PR as you noted it has nothing to do with this PR the ticket is here https://trello.com/c/u77EN6cT

**Pull request merged**
