### PR TITLE
Add consistency and UI improvements

### PR DESCRIPTION
**Pull request by Mubangizi**
# Description
This PR creates consistency for components and color themes more on details are:
- Replaces all occurrences of color codes for primary and secondary colors with variables.
- Adds new Layout component `DashboardLayout` and wraps all project and app pages with this component
- Adds UI changes to the Creare project Page, Search bar and project Card.
- Reduces Icons on the homepage
- Reduces sidebar icon sizes
- Creates a dynamic `PrimaryButton` component

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## How Can This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test scenario/configuration

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots

### CODE REVIEW

**Comment by neelxie** [comment]
@Mubangizi could you kindly rectify the 6 broken tests that broke the build. Plus changes to the buttons have both a border and an outline showing
WhatsApp Image 2022-12-04 at 6 07 22 PM
WhatsApp Image 2022-12-04 at 6 06 49 PM

**Comment by Mubangizi** [comment]
> @Mubangizi could you kindly rectify the 6 broken tests that broke the build. Plus changes to the buttons have both a border and an outline showing WhatsApp Image 2022-12-04 at 6 07 22 PM WhatsApp Image 2022-12-04 at 6 06 49 PM

This should be fixed @neelxie

**Review by neelxie — DISMISSED** [review]
@Mubangizi good work on this

**Comment by khalifan-kfan** [comment]
Looks nice @Mubangizi 
just a few small coments 
on the Loading database settings page, there is a gap that comes up above the information bar
image

On scrolling down on the project settings page
image

**Comment by Mubangizi** [comment]
> Looks nice @Mubangizi just a few small coments on the Loading database settings page, there is a gap that comes up above the information bar image
> 
> On scrolling down on the project settings page image

Hey @khalifan-kfan, I am not able to recreate this. Are you sure you are running with the latest commits? Just asking?

**Review by neelxie — APPROVED** [review]
Thanks for the fixes

**Review by rhodinemma — APPROVED** [review]
Thank you for the improvements @Mubangizi

**Review by khalifan-kfan — APPROVED** [review]
Looks neat, thanks

**Pull request merged**
