### PR TITLE
Add db support

### PR DESCRIPTION
**Pull request by StephenAraka**
### What this does?
On create app form, this adds checkbox for database support

### Also:
- adds 2 input fields for entry command and port

### Screenshot
Screenshot from 2020-04-28 22-27-22

### CODE REVIEW

**Comment by Mubangizi** [comment]
Hey @StephenAraka  the entry command input should be below the `db support` text, and should only be activated if the checkbox is ticked. What do you think?

**Comment by inno-asiimwe** [comment]
@Mubangizi the `entry command` is independent of `db support`, it only happened that the backend added them at the same time.

**Comment by inno-asiimwe** [comment]
@StephenAraka `entry command` should be optional as well.

**Comment by Mubangizi** [comment]
> @StephenAraka `entry command` should be optional as well.

My query is, is it dependent on need for db-support? As-in can you have an `entry command` without the `db support`

**Comment by StephenAraka** [comment]
> > @StephenAraka `entry command` should be optional as well.
> 
> My query is, is it dependent on need for db-support? As-in can you have an `entry command` without the `db support`?

Yes, You can have entry command without db support.

**Comment by StephenAraka** [comment]
> you need to pull in remote changes first. your pr lacks work from both @Mubangizi and @mrwagaba

I will... still got some WIP

**Comment by StephenAraka** [comment]
Apologies for the many commits... These are as a result of rebasing with `develop-new` after a long time. Definitely won't be happening again.

**Pull request merged**
