### PR TITLE
add date to transactions

### PR DESCRIPTION
**Pull request by khalifan-kfan**
# Description

Add dates data at the frontend as from the api

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Trello Ticket ID

https://trello.com/c/sdjhy3ZK

## How Can This Been Tested?

the Pull the branch and checkout the billing page in search for transactions and transaction details

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots
image

### CODE REVIEW

**Review by rhodinemma — COMMENTED** [review]
Good job adding the Date field but is the time extension necessary? because ideally the field identifies "Date" and not "Date-and-Time".

**Comment by khalifan-kfan** [comment]
> Good job adding the Date field but is the time extension necessary? because ideally the field identifies "Date" and not "Date-and-Time".

sure

**Review by rhodinemma — APPROVED** [review]

**Review by e-ian — APPROVED** [review]
LGTM

**Review by MutegekiHenry — APPROVED** [review]
looks good

**Pull request merged**
