### PR TITLE
Fix custom date

### PR DESCRIPTION
**Pull request by mirembe-mariam**
# Description

- A user's selected date under custom on project CPU, network, and memory is shown 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Trello Ticket ID

https://trello.com/c/s0iN49TJ

## How Can This Been Tested?

Run this branch and access the project CPU, Memory, and Network Pages, and select dates under custom

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# Screenshots

Screenshot from 2023-11-16 10-25-19

### CODE REVIEW

**Review by neelxie — DISMISSED** [review]
LGTM

**Review by mosesmulumba — COMMENTED** [review]
I have seen the modal for the custom date is not aligned well. Maybe take some time to align it.

**Review by khalifan-kfan — APPROVED** [review]
Nice @mirembe-mariam , though the display design for the current date can be displayed better.

**Review by neelxie — APPROVED** [review]
LGTM

**Pull request merged**
