### PR TITLE
Create Table List component

### PR DESCRIPTION
**Pull request by neelxie**
#### What does this PR do?

Table List Component

#### Description of Task to be completed?
- Create the re-usable table component

#### How should this be manually tested?

* Pull Check it out this branch

staffa

### CODE REVIEW

**Comment by Mubangizi** [comment]
I think you should first finish your feature then make a PR.
I don't expect to see more commits except if there from feedback.
I think that's a better flow we review, then your over write our approvals with new changes

**Comment by neelxie** [comment]
> I think you should first finish your feature then make a PR.
> I don't expect to see more commits except if there from feedback.
> I think that's a better flow we review, then your over write our approvals with new changes

@Mubangizi kindly be specific and detailed in your communication, if I am not wrong I believe this feature was finished hence the PR. Kindly do review and leave feedback.

**Comment by neelxie** [comment]
> @neelxie i dont see an endpoint to test this page

@MutegekiHenry that is true, this is because it is a re-usable table component. If you had been keen enough you would have noted that its being tested out in the admin dash component, kind regards.

**Comment by Mubangizi** [comment]
@neelxie  how should one run this branch because am not clear the required props to send to the table. As-in i didn't get it

**Comment by Mubangizi** [comment]
> > I think you should first finish your feature then make a PR.
> > I don't expect to see more commits except if there from feedback.
> > I think that's a better flow we review, then your over write our approvals with new changes
> 
> @Mubangizi kindly be specific and detailed in your communication, if I am not wrong I believe this feature was finished hence the PR. Kindly do review and leave feedback.

**Comment by Mubangizi** [comment]
Mistake Sorry

**Comment by Mubangizi** [comment]
Alright i see it works fine. Thumbs up

**Pull request merged**
