### PR TITLE
Implement login page

### PR DESCRIPTION
**Pull request by StephenAraka**
### What does this PR do?
Add login page

### Description of the task to be completed?
Create the landing page

### FROM DESIGN (expected)
Screenshot from 2020-02-17 14-25-00

### CURRENT OUTPUT (how it looks)
Screenshot from 2020-02-17 14-33-57

### How should this be manually tested?
- pull and run the branch

### Some background context.
- Also modified the router.js file
- Added routes for login and home page

### CODE REVIEW

**Comment by mwotil** [comment]
@StephenAraka - I think 'Login to the cloud' may be redundant - lets just have it as Login. Also we on the same Login Page, I think the top nav bar should change to Register and when on the Register Page it should be Login. Also we need consistency in the names for example Login and Register go hand in hand while Sign Up and Sign is the other pair

**Comment by StephenAraka** [comment]
> @StephenAraka you forgot the interactions for the links as we discussed with @ckwagaba

I have no idea about these interactions. Are they for the **PRICING** & **DOCS** links? ...

**Comment by StephenAraka** [comment]
> @StephenAraka - I think 'Login to the cloud' may be redundant - lets just have it as Login. Also we on the same Login Page, I think the top nav bar should change to Register and when on the Register Page it should be Login. Also we need consistency in the names for example Login and Register go hand in hand while Sign Up and Sign is the other pair

@mwotil Thanks for the feedback! Makes sense... @ckwagaba the designer can weigh in on this, then with his approval, we will make the suggested changes.

**Comment by neelxie** [comment]
> > @StephenAraka you forgot the interactions for the links as we discussed with @ckwagaba
> 
> @neelxie I have no idea about these interactions. Are they for the **PRICING** & **DOCS** links? ...

@StephenAraka  the links that are underlined with the orange color, we had discussed the underline off as their second state for the interactions.

**Comment by mwotil** [comment]
What was @ckwagaba comment on my suggestion? I still think we should just maintain Login

**Pull request merged**
