### PR TITLE
Add database password copying

### PR DESCRIPTION
**Pull request by neelxie**
#### What does this PR do?
It adds provision for copying a password
#### Ticket
https://trello.com/c/DhaB70UQ

#### Screenshots
Screenshot from 2021-05-03 12-21-45
Screenshot from 2021-05-03 12-22-06
Screenshot from 2021-05-03 12-22-10

### CODE REVIEW

**Comment by Mubangizi** [comment]
I feel link you need to put `copy` for every value because there all very long. Otherwise, good stuff man

**Comment by neelxie** [comment]
> I feel link you need to put `copy` for every value because there all very long. Otherwise, good stuff man

@Mubangizi are you sure its not available on staging sir, checkout staging first sir. :100:

**Review by kawerewagaba — CHANGES_REQUESTED** [review]
i think there's an underlying thing u gotta fix. the password copy works tho

**Comment by neelxie** [comment]
> i think there's an underlying thing u gotta fix. the password copy works tho

@kawerewagaba could you kindly make your comment more actionable?

**Comment by neelxie** [comment]
> Screenshot 2021-05-06 at 19 28 28
> 
> Screenshot 2021-05-06 at 19 28 47ype
> 
> pr shows types, but all are `mysql`

@kawerewagaba the issue raised by you here are beyond the scope of this PR.

**Review by kawerewagaba — APPROVED** [review]

**Pull request merged**
