### PR TITLE
Ft add project description

### PR DESCRIPTION
**Pull request by neelxie**
image

### CODE REVIEW

**Comment by neelxie** [comment]
> @neelxie when i try to update a project in your branch i get this error
> Screenshot from 2020-04-27 13-51-56
> 
> Also, i noticed your config has the base URL directly placed hope that can be changed before the merge

@MutegekiHenry let me check this out and see

**Comment by neelxie** [comment]
> @neelxie when i try to update a project in your branch i get this error
> Screenshot from 2020-04-27 13-51-56
> 
> Also, i noticed your config has the base URL directly placed hope that can be changed before the merge

@MutegekiHenry could you kindly re-pull the branch and test it, because it works fine on my end.

**Comment by MutegekiHenry** [comment]
> > @neelxie when i try to update a project in your branch i get this error
> > Screenshot from 2020-04-27 13-51-56
> > Also, i noticed your config has the base URL directly placed hope that can be changed before the merge
> 
> @MutegekiHenry could you kindly re-pull the branch and test it, because it works fine on my end.

Still throwing that error in this branch and develop works well for current implementation of update project name

**Comment by neelxie** [comment]
> > > @neelxie when i try to update a project in your branch i get this error
> > > Screenshot from 2020-04-27 13-51-56
> > > Also, i noticed your config has the base URL directly placed hope that can be changed before the merge
> > 
> > 
> > @MutegekiHenry could you kindly re-pull the branch and test it, because it works fine on my end.
> 
> Still throwing that error in this branch and develop works well for current implementation of update project name. Maybe others can try on their end, it could be my PC

@MutegekiHenry lets wait on them if it persists when could have a call.

**Comment by StephenAraka** [comment]
Getting an error....
Screenshot from 2020-04-28 14-22-49

You could consider getting a project's details from localStorage... and also, endeavour to clean up your code to the max.

**Comment by neelxie** [comment]
> @neelxie I'm getting an error...
> Screenshot from 2020-04-28 14-22-49
> 
> You could consider getting a project's details from localStorage given it's already there in state... and also, endeavour to clean up your code to the max...

@StephenAraka let me re-pull my branch and let you know.

**Comment by neelxie** [comment]
> > @neelxie I'm getting an error...
> > Screenshot from 2020-04-28 14-22-49
> > You could consider getting a project's details from localStorage given it's already there in state... and also, endeavour to clean up your code to the max...
> 
> @StephenAraka let me re-pull my branch and let you know.

@StephenAraka I have fixed this issue, do check it out.

**Comment by StephenAraka** [comment]
Hey @neelxie , I have pulled changes but I am still getting the same issue...

**Comment by neelxie** [comment]
> Hey @neelxie , I have pulled changes but I am still getting the same issue...

Can we set up a call, because everything seems to run and work fine on my end.

**Comment by MutegekiHenry** [comment]
@neelxie thanks for the changes, it now works on my end, just two things to point out:

1. it doesn't allow someone to only update one field it seems you made both fields mandatory
2.  it lacks error messages to give user feedback for example when I try to rename a project with an existing name, it causes a 409 but the user doesn't see anything

**Comment by neelxie** [comment]
> @neelxie thanks for the changes, it now works on my end, just two things to point out:
> 
> 1. it doesn't allow someone to only update one field it seems you made both fields mandatory
> 2. it lacks error messages to give user feedback for example when I try to rename a project with an existing name, it causes a 409 but the user doesn't see anything

@MutegekiHenry let me work on this feedback, thank you.

**Comment by neelxie** [comment]
> @neelxie thanks for the changes, it now works on my end, just two things to point out:
> 
> 1. it doesn't allow someone to only update one field it seems you made both fields mandatory
> 2. it lacks error messages to give user feedback for example when I try to rename a project with an existing name, it causes a 409 but the user doesn't see anything

@MutegekiHenry 
image
 and this boss

**Comment by neelxie** [comment]
> @neelxie thanks for the changes, it now works on my end, just two things to point out:
> 
> 1. it doesn't allow someone to only update one field it seems you made both fields mandatory
> 2. it lacks error messages to give user feedback for example when I try to rename a project with an existing name, it causes a 409 but the user doesn't see anything

@MutegekiHenry kindly recheck this and let me know sir.

**Comment by Mubangizi** [comment]
Great stuff @neelxie, i see it works fine, though i have one more request for you. 
Make the input `placeholders` for update be the text of the project. like in `Project name`, make  its placeholder name the current name of the project.

**Pull request merged**
