### PR TITLE
handle success and failure on submit create project

### PR DESCRIPTION
**Pull request by MutegekiHenry**
### What does this PR do?
It handles the success and error messages on after making requests to API to create Project

### How should it be tested?
Pull and run branch locally, then create a project and look out for the success message, also try to create another project with the same name and look out for the failure message.

### Screenshots?
1. This is on successful creation
onsuccessPrjct

2. On failure due to unique project names
a) List of existing projects
list of projects

b) Try to create a new project with the name Henry which is for an existing project.
attempt2recreate

### CODE REVIEW

**Comment by mwotil** [comment]
All the fields are required, right? And the checks such as field lengths are in place for that. On my side, it should be good to go. I guess the projects page is being handled in another PR (if the description is too long, I think it may cause some overlaps in the display)

**Comment by MutegekiHenry** [comment]
> All the fields are required, right? And the checks such as field lengths are in place for that. On my side, it should be good to go. I guess the projects page is being handled in another PR (if the description is too long, I think it may cause some overlaps in the display)

The validation for the Form fields are in another PR which is also up for review, this particular PR only handles the messages the user receives after communicating to the API to create a project. Ideally, this will only happen when the form validations have passed, though they are handled in a separate PR.

**Comment by Mubangizi** [comment]
I still wonder why you dint do all this in the same PR

**Comment by Mubangizi** [comment]
Hey @MutegekiHenry  while your at it, please add the loading `spinner` for when the project is being created.

**Comment by MutegekiHenry** [comment]
> Hey @MutegekiHenry while your at it, please add the loading `spinner` for when the project is being created.

@Mubangizi sure let me add that

**Pull request closed without merging**
