### PR TITLE
feature cluster resources page

### PR DESCRIPTION
**Pull request by neelxie**
#### What does this PR do?

Create a cluster resources page

#### Description of Task to be completed?
- Create the UI for the page 
- Integrate API calls within the UI

#### How should this be manually tested?

* Check it out here. locally and navigate to the url `/resources`

#### Screenshots
page

### CODE REVIEW

**Comment by mwotil** [comment]
Could you change the 'Header' to 'Cluster Resources'

**Comment by neelxie** [comment]
> Could you change the 'Header' to 'Cluster Resources'

@mwotil this has been worked on here
image

**Comment by Mubangizi** [comment]
@neelxie  from the design, resource counts are not bold and no shadow on the cards
other wise good stuff

**Comment by neelxie** [comment]
> @neelxie from the design, resource counts are not bold and no shadow on the cards
> other wise good stuff

@Mubangizi thank you for pointing that out I have fixed it.

**Comment by neelxie** [comment]
> Hey @neelxie there some conflicts on your branch that come through after merging log-in branch, lets resolve them together cause if deleted they shall affect our current code

@MutegekiHenry this has been fixed.

**Comment by Mubangizi** [comment]
Hey @neelxie  please re-base and merge this PR

**Comment by Mubangizi** [comment]
Is this PR ready to be Merged or?

**Comment by Mubangizi** [comment]
Side Nav has been changed on the base branch so you need to see how that affects your implementation of is

**Comment by Mubangizi** [comment]
Alright i see it works fine. Thumbs up

**Pull request merged**
