### PR TITLE
Feat View all your projects as a User

### PR DESCRIPTION
**Pull request by neelxie**
#### What does this PR do?

Vies your projects

#### Description of Task to be completed?
- Display a users specific projects

#### How should this be manually tested?

* Check it out here.
**NOTE that this PR makes use of functionality in the auth PR to pick user ID to add it to the backend route for the feature. So to perfectly run it, FOR NOW, you will have to manually put the user ID in the route to see the feature working perfectly**

#### Screenshots

image

### CODE REVIEW

**Comment by StephenAraka** [comment]
> I have reviewed this... Looks good. I changed the router file. Must be why there are conflicts. Let me just check them out.

@neelxie So, I've protected the route for user projects.

**Comment by neelxie** [comment]
> > I have reviewed this... Looks good. I changed the router file. Must be why there are conflicts. Let me just check them out.
> 
> @neelxie So, I've protected the route for user projects.

@StephenAraka perfect am on it

**Comment by inno-asiimwe** [comment]
@StephenAraka could we have this reviewed as well, and merged. cc @neelxie

**Comment by neelxie** [comment]
> @StephenAraka could we have this reviewed as well, and merged. cc @neelxie

@inno-asiimwe https://github.com/crane-cloud/frontend/pull/76 is more urgent priority than this.

**Pull request merged**
