### PR TITLE
adding password requirements on the registry form

### PR DESCRIPTION
**Pull request by mosesmulumba**
# Description

This pull request targets to secure the user accounts by prompting and requiring them register with strong and long enough passwords to the platform. The passwords are targeted to have a minimum of 8 characters , at least an uppercase , lowercase letter and a number.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Trello Ticket ID

https://trello.com/c/8B48LUIM

## How Can This Been Tested?

Pull the remote branch and run it locally. Try registering a new account with a short password, or even registering with one that lacks the uppercase , lowercase and number. You will be prompted to fulfill the requirements.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots

Screenshot from 2024-03-22 16-09-40

### CODE REVIEW

**Comment by neelxie** [comment]
@mosesmulumba please padding for the error message div, plus most importantly, make sure your tests ain't failing.

**Review by neelxie — DISMISSED** [review]
Tests seem to be failing.

**Comment by mosesmulumba** [comment]
Yeah I realized that, I tried  to run them again but still the same issue.

**Comment by mosesmulumba** [comment]
But I am gonna work on that.

**Review by rhodinemma — CHANGES_REQUESTED** [review]
Thanks for this @mosesmulumba, my comment is similar, let us give that warning message a padding all-round, then for tests you need to validate the changes you added in the equivalent test file - 

Screenshot 2024-03-23 at 11 52 52 AM

But we can schedule time next week and we look at it together!

**Review by rhodinemma — APPROVED** [review]
Thanks for adding the password requirements @mosesmulumba 
..the unit tests are now passing too!

**Review by khalifan-kfan — APPROVED** [review]

**Pull request merged**
