### PR TITLE
Change Add App modal layout

### PR DESCRIPTION
**Pull request by StephenAraka**
### what does this PR do?
adjust modal as mentioned in feedback...
1. restore the size of the input fields and buttons as they are in the rest of the app
2. make content scrollable 
3. make buttons stick to bottom of the form

### BEFORE
Screenshot from 2020-04-01 16-01-43

### AFTER
Screenshot from 2020-04-01 15-38-00
Screenshot from 2020-04-01 15-37-47

### CODE REVIEW

**Comment by Mubangizi** [comment]
Those `Env`  fields look too big

**Comment by StephenAraka** [comment]
> Hey @StephenAraka, I did see the model and i still think that the `env` fields seem too big.
> But putting that aside, For User experience, please add hover effects on both the `ADD` and the `X` buttons for the `env` fields. You could maib add a simple `highlight` or `transparency` on `hover`.
> Thank you though, Great work.

Hey @Mubangizi , thanks for the feedback... I will add the hover effects. As for the env var inputs, the team earlier suggested that all inputs should be the same size throughout the app...

**Comment by StephenAraka** [comment]
@Mubangizi I've added the hover effects...

**Comment by StephenAraka** [comment]
Just discovered an issue on this...
Removing the ready for review label for now...
I'll fix this 1st ...
Screenshot from 2020-04-02 22-17-30

**Pull request merged**
