### PR TITLE
Redesign the project details page

### PR DESCRIPTION
**Pull request by ArnaudBand**
# Description

Implement the new designs for project details on the admin side

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Trello Ticket ID

[Trello ticket for the task.](https://trello.com/c/T1tolRBc)

## How Can This Been Tested?

You can pull this branch and run it locally.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots

Screenshot from 2023-08-28 15-40-51

image

### CODE REVIEW

**Review by rhodinemma — APPROVED** [review]
Thank you for this @ArnaudBand

**Review by khalifan-kfan — COMMENTED** [review]
Nicely done @ArnaudBand, Try to center the loader before the project details appear 
And also the responsiveness, please
Screenshot 2023-08-29 at 23 21 17

**Comment by khalifan-kfan** [comment]
Also please work to maintain a single CSS file for each component. @ArnaudBand

**Review by rhodinemma — DISMISSED** [review]
Looks good now.

**Comment by khalifan-kfan** [comment]
Worked on the feedback requested @ArnaudBand 
Please review again @rhodinemma

**Review by rhodinemma — APPROVED** [review]

**Review by mirembe-mariam — APPROVED** [review]

**Pull request merged**
