### PR TITLE
Change admin projects view, from Card view to List View

### PR DESCRIPTION
**Pull request by Mubangizi**
#### What this PR Does
- Changes Admin Project view to list view
- Adds Project Owners to projects list.

#### Screenshots
Screenshot from 2020-04-09 16-32-31

### CODE REVIEW

**Comment by Mubangizi** [comment]
> @Mubangizi the PR description doesnt exactly match the written code, you code seems to cover 3 different features with 2 of them halfway done, kindly consider separation of concerns to have a more concise and specific understanding for us teammates to understand what you are working on, for example, this PR makes code for the users list feature, a feature I had created a ticket to work on. Let us have a clear easy to follow workflow, create a ticket for a feature, work on that pick another instead of what you have here, Kindly notify me whether to abandon my users list feature or not, thank you.

Yes @neelxie  you can abandon your users list because i have created it in `here`. And there is nothing that i did that is out of the scope for this PR, i need to retrieve users list to get the `user owner names` that are shown in the `projects page`. So to be sincere i don't get the changes you want me to make

**Comment by MutegekiHenry** [comment]
> > @Mubangizi the PR description doesnt exactly match the written code, you code seems to cover 3 different features with 2 of them halfway done, kindly consider separation of concerns to have a more concise and specific understanding for us teammates to understand what you are working on, for example, this PR makes code for the users list feature, a feature I had created a ticket to work on. Let us have a clear easy to follow workflow, create a ticket for a feature, work on that pick another instead of what you have here, Kindly notify me whether to abandon my users list feature or not, thank you.
> 
> Yes @neelxie you can abandon your users list because i have created it in `here`. And there is nothing that i did that is out of the scope for this PR, i need to retrieve users list to get the `user owner names` that are shown in the `projects page`. So to be sincere i don't get the changes you want me to make

@Mubangizi for some reason i get a **TypeError: users.users is undefined**  when i click the projects tab via admin dashboard

**Comment by StephenAraka** [comment]
> > > @Mubangizi the PR description doesnt exactly match the written code, you code seems to cover 3 different features with 2 of them halfway done, kindly consider separation of concerns to have a more concise and specific understanding for us teammates to understand what you are working on, for example, this PR makes code for the users list feature, a feature I had created a ticket to work on. Let us have a clear easy to follow workflow, create a ticket for a feature, work on that pick another instead of what you have here, Kindly notify me whether to abandon my users list feature or not, thank you.
> > 
> > 
> > Yes @neelxie you can abandon your users list because i have created it in `here`. And there is nothing that i did that is out of the scope for this PR, i need to retrieve users list to get the `user owner names` that are shown in the `projects page`. So to be sincere i don't get the changes you want me to make
> 
> @Mubangizi for some reason i get a **TypeError: users.users is undefined** when i click the projects tab via admin dashboard

Same... 
Screenshot from 2020-04-14 16-04-21
@Mubangizi 1st fix this...

**Comment by Mubangizi** [comment]
> > @Mubangizi for some reason i get a **TypeError: users.users is undefined** when i click the projects tab via admin dashboard
> 
> Same...
> Screenshot from 2020-04-14 16-04-21
> @Mubangizi 1st fix this...

i have fixed the issue, thank you for pointing it out

**Comment by Mubangizi** [comment]
But we said if am not creating a new connection, i dont need to touch it. And i pretty much dont know what to delete, so as we had agreed, a PR will fix all that stuff.

**Pull request merged**
