### PR TITLE
Feature Volumes list as Admin

### PR DESCRIPTION
**Pull request by neelxie**
#### What does this PR do?

List volumes in a cluster

#### Description of Task to be completed?
- Display volume lists in the admin dash

#### How should this be manually tested?

* Check it out here.

#### Screenshots
image

### CODE REVIEW

**Comment by Mubangizi** [comment]
Here is an idea of what am talking about.
Screenshot from 2020-03-05 12-23-21

**Comment by neelxie** [comment]
> Hey, there is more crucial information that your still missing on `PV`s
> 1 - I need to see the `Capacity` of the PV.
> 2 - I need to see what is Claiming the `Persistent Volume`.
> 3 - I need to see its `Access Mode` for Writing and reading from Nodes.
> 
> > They include:
> > RWO - ReadWriteOnce
> > ROX - ReadOnlyMany
> > RWX - ReadWriteMany
> 
> 4 - The PVs `Reclaim Policy` What measures it takes when it terminates there; `retain`, `recycle` and `delete`.
> I hope that explains it well enough.
> Those fields are important please consider adding them Thank you

@Mubangizi kindly point out specifically how many columns I need to add because I doubt that the four columns you are suggesting are viable. Thank you.

**Comment by neelxie** [comment]
> Here is an idea of what am talking about.
> Screenshot from 2020-03-05 12-23-21

@Mubangizi please do keep in mind that the kubernetic interface and results dont set precedence for our UI, that is why we have a designer for this, and if you have been keen enough you will notice that it returns a bunch of other things for things like nods, pods but are not included in our design, that doesnt make those attributes shown through kubernetic any less useful.

**Comment by neelxie** [comment]
> > Here is an idea of what am talking about.
> > Screenshot from 2020-03-05 12-23-21
> 
> @Mubangizi please do keep in mind that the kubernetic interface and results dont set precedence for our UI, that is why we have a designer for this, and if you have been keen enough you will notice that it returns a bunch of other things for things like nods, pods but are not included in our design, that doesnt make those attributes shown through kubernetic any less useful.

@Mubangizi kindly recheck the PR image I have worked on your feedback

**Comment by Mubangizi** [comment]
@neelxie this information is for The Cluster Admin, please dont forget that. From what you have made  as a cluster Admin i dont see much useful information other than `Capacity`. In my view you have to Add `Access Modes` and `Reclaim Policy`.

**Comment by neelxie** [comment]
> @neelxie this information is for The Cluster Admin, please dont forget that. From what you have made as a cluster Admin i dont see much useful information other than `Capacity`. In my view you have to Add `Access Modes` and `Reclaim Policy`.

@Mubangizi @StephenAraka @MutegekiHenry this has been fixed
image

**Comment by neelxie** [comment]
> @neelxie Great stuff. Thank you for working on the feedback.
> But, you would rather drop `Status` column (I dont even think it is relevant) and replace it with the one of the `Capacity`, that shows how big the volume is. Thank you

@Mubangizi sadly I will not be able to implement that for two reasons,

1. Your prior feedback requested I add the capacity column, and I did. You later stated that it did not serve any purpose and you wanted it to be removed, I still did that. And now you want it back? Personally I just think you are trying to have this PR up longer without a valid reason, this is called nitpicking --google it.

2. Professionally in the absence of a design for a feature whoever undertakes to work on it is at liberty to exercise his creativity on that feature and any design changes contrary to his/her require approvals from at least 3 members of the team. So for whatever you want kindly raise it in the slack channel and if 3 people approve it, I will gladly work on it.

**Comment by Mubangizi** [comment]
> > @neelxie Great stuff. Thank you for working on the feedback.
> > But, you would rather drop `Status` column (I dont even think it is relevant) and replace it with the one of the `Capacity`, that shows how big the volume is. Thank you
> 
> @Mubangizi sadly I will not be able to implement that for two reasons,
> 
> 1. Your prior feedback requested I add the capacity column, and I did. You later stated that it did not serve any purpose and you wanted it to be removed, I still did that. And now you want it back? Personally I just think you are trying to have this PR up longer without a valid reason, this is called nitpicking --google it.
> 2. Professionally in the absence of a design for a feature whoever undertakes to work on it is at liberty to exercise his creativity on that feature and any design changes contrary to his/her require approvals from at least 3 members of the team. This ensures that one's creativity is not undermined. So for whatever you want kindly raise it in the slack channel and if 3 people approve it, I will gladly work on it.

@neelxie  First of all, I dont think there is a time when i told you i dont need the `Capacity` Field, that am real sure. About `PRs` what do i gain from this PR staying up for long? Realy?

Just saying i will only approve it if `Capacity` Field is up am sorry. I kindly asked for specifically 3 fields: `Capacity`, `Access Modes` and `Reclaim Policy`. You only implemented 2, I dont know when I told you to remove the other one.

**Comment by neelxie** [comment]
> > > @neelxie Great stuff. Thank you for working on the feedback.
> > > But, you would rather drop `Status` column (I dont even think it is relevant) and replace it with the one of the `Capacity`, that shows how big the volume is. Thank you
> > 
> > 
> > @Mubangizi sadly I will not be able to implement that for two reasons,
> > 
> > 1. Your prior feedback requested I add the capacity column, and I did. You later stated that it did not serve any purpose and you wanted it to be removed, I still did that. And now you want it back? Personally I just think you are trying to have this PR up longer without a valid reason, this is called nitpicking --google it.
> > 2. Professionally in the absence of a design for a feature whoever undertakes to work on it is at liberty to exercise his creativity on that feature and any design changes contrary to his/her require approvals from at least 3 members of the team. This ensures that one's creativity is not undermined. So for whatever you want kindly raise it in the slack channel and if 3 people approve it, I will gladly work on it.
> 
> @neelxie First of all, I dont think there is a time when i told you i dont need the `Capacity` Field, that am real sure. About `PRs` what do i gain from this PR staying up for long? Realy?
> 
> Just saying i will only approve it if `Capacity` Field is up am sorry. I kindly asked for specifically 3 fields: `Capacity`, `Access Modes` and `Reclaim Policy`. You only implemented 2, I dont know when I told you to remove the other one.

@Mubangizi thank you for your feedback you dont have to approve this PR and I am not adding it, ,

**Pull request merged**
