### PR TITLE
ft User verification

### PR DESCRIPTION
**Pull request by StephenAraka**
### what does this PR do?
1. User Verification process i.e Sign Up
2. Login
3. Logout

### Also
4. I made some changes to the Header / TopBar / TopNav (that ka bar on top)

### Screenshots?
They won't upload, I sometimes have this issue on Github ... dunno why

### Testing
Please run the branch...
**IMPORTANT**... to view full functionality, use your email to Sign Up so that you can receive the verification link

### CODE REVIEW

**Comment by StephenAraka** [comment]
> @StephenAraka great work, so i have gone through the user journey, its all good, just one quick comment, the link i received at my email logged me in directly, yet i had thought it takes me to a login page? since in the near future, we may have two different login pages for admin and user.

Hey @MutegekiHenry thanks for the review... about the link logging you in, it is intended to do that.
Remember we said admins will have their own route. And also, I think the distinctness of these user roles will be later refined.

**Comment by StephenAraka** [comment]
> @StephenAraka this works perfectly but when I login in and reroute to the landing page the logout functionality doesnt work, and how doI navigate back to my dashboard?
> image

Thanks for the review @neelxie ... The functionality is there but I still have a lot of underlying issues to fix... I will work on those.

**Comment by StephenAraka** [comment]
> @StephenAraka this works perfectly but when I login in and reroute to the landing page the logout functionality doesnt work, and how doI navigate back to my dashboard?
> image

Screenshot from 2020-03-11 16-09-25

So, this has been changed... currently it's like this...

**Comment by StephenAraka** [comment]
Screenshot from 2020-03-12 15-52-10

Now we have a separate login for the admin

**Comment by StephenAraka** [comment]
I have realized that there is some Css that is messed up.... e.g someone cannot log out via a dashboard page. The drop down doesnt display as it should.
But I request that this be changed in a subsequent PR. Lets 1st merge this PR.

**Comment by inno-asiimwe** [comment]
@neelxie @Mubangizi  we need this reviewed and merged ASAP.

**Pull request merged**
