### PR TITLE
Create app memory metrics page

### PR DESCRIPTION
**Pull request by neelxie**
#### What does this PR do?

It creates an app memory metrics page.
#### Screenshots
Screenshot from 2020-09-16 22-38-35

### CODE REVIEW

**Comment by StephenAraka** [comment]
@neelxie Are those the correct memory values in MBs?

**Comment by neelxie** [comment]
> @neelxie Are those the correct memory values in MBs? If yes, we should multiply the values to have them display fewer decimals?

I believe such a such would have to cut across not just at the application level but as well as at the project level and that all entails in the general graph component re-implementation discussion we ought to have, and discuss what multipliers are suitable. @StephenAraka

**Comment by StephenAraka** [comment]
> > @neelxie Are those the correct memory values in MBs? If yes, we should multiply the values to have them display fewer decimals?
> 
> I believe such a suggestion would have to cut across not just at the application level but as well as at the project level and that all entails in the general graph component re-implementation discussion we ought to have, and discuss what multipliers are suitable. @StephenAraka

okay, let me approve this. since that will be discussed and modified later. Good job

**Review by StephenAraka — DISMISSED** [review]

**Review by MutegekiHenry — APPROVED** [review]
Looks good to go

**Review by StephenAraka — APPROVED** [review]

**Review by MutegekiHenry — APPROVED** [review]

**Pull request merged**
