### PR TITLE
Fix Staging UI issues

### PR DESCRIPTION
**Pull request by Mubangizi**
# Description
Makes application pages more symmetrical

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
.

## How Can This Been Tested?
Run branch locally then go through the application and see the new changes

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots
These are upcoming

### CODE REVIEW

**Review by neelxie — APPROVED** [review]
Lgtm

**Comment by khalifan-kfan** [comment]
nice designs. But apps not rendering on project dashboard
image

**Review by khalifan-kfan — DISMISSED** [review]

**Review by neelxie — APPROVED** [review]
Very many files, thankful code still runs well, LGTM

**Review by rhodinemma — APPROVED** [review]
Works fine.

**Pull request merged**
