### PR TITLE
Single Database Activity

### PR DESCRIPTION
**Pull request by neelxie**
#### What does this PR do?
It creates a page that has a single database view and also incorporates the database reset and database deletion.

#### How to test this PR?
1. Pull this branch
2. Go to your project and on under the sidebar click "databases"
3. You will be able to see a list to all databases.
4. Click on one and you will be re-directed to the single database view.
5. At the bottom of the page lies the delete and reset button click them and test their functionality
6. **Note** use Henry's account to test this out as there lots of databases you can delete plus `DO RUN THE PR LOCALLY!`

#### Ticket 
https://trello.com/c/N1KD8skR

#### Screenshots
Screenshot from 2021-03-11 14-52-44
Screenshot from 2021-03-11 15-29-24
Screenshot from 2021-03-11 19-38-10

### CODE REVIEW

**Review by MutegekiHenry — APPROVED** [review]
@neelxie great work on this. The only thing that could be an issue would be the fact that there is no feedback to the user after the reset has been effected, maybe that could come in a different PR.

**Review by Mubangizi — APPROVED** [review]
Great work @neelxie

**Comment by kawerewagaba** [comment]
Let's work on the conflicts first, which could also explain why the create button is no longer working after pulling this branch. I successfully created with the previous branch, pulled this branch, clicked the db, saw the details, and successfully deleted. However, I could not create after that!
Screenshot 2021-03-18 at 07 17 23

**Comment by kawerewagaba** [comment]
Screenshot 2021-03-18 at 08 24 08
we shall also need to look into this at some point... state management

**Review by kawerewagaba — APPROVED** [review]
looks good for now

**Comment by neelxie** [comment]
> Screenshot 2021-03-18 at 08 24 08
> 
> we shall also need to look into this at some point... state management

Reading about this now, but I don't have a function triggering that but let me keep digging.

**Comment by kawerewagaba** [comment]
It's just state management, will investigate later!

**Pull request merged**
