### PR TITLE
Create project metrics page

### PR DESCRIPTION
**Pull request by neelxie**
#### What does the PR do?
It creates a project metrics page showing a combination of all the project's metrics like Memory, Network and CPU

#### Screenshots
Screenshot from 2020-09-03 20-19-37

### CODE REVIEW

**Comment by mrwagaba** [comment]
Screenshot 2020-09-04 at 08 49 45
Too many errors on the PR. Resolve them first.

**Comment by mrwagaba** [comment]
Screenshot 2020-09-04 at 10 05 26
Why this `404` tho

**Comment by mrwagaba** [comment]
Screenshot 2020-09-04 at 10 06 54
Also the design is off - revisit the borders for the cards.
Screenshot 2020-09-04 at 10 08 35

**Comment by neelxie** [comment]
> Screenshot 2020-09-04 at 10 06 54
> 
> Also the design is off - revisit the borders for the cards.
> Screenshot 2020-09-04 at 10 08 35

@mrwagaba this has been worked on and fixed.

**Review by StephenAraka — APPROVED** [review]

**Review by MutegekiHenry — APPROVED** [review]

**Pull request merged**
