### PR TITLE
Filter project memory by period

### PR DESCRIPTION
**Pull request by StephenAraka**
### What does this PR do?
Enable filtering project memory graph by predefined periods

### Some useful context
The feature focuses on only implementing the period component... Details like graph axis values and labels to be handled in other PRs

### Screenshot
**1DAY** Screenshot from 2020-08-26 19-53-50
**1WEEK** Screenshot from 2020-08-26 19-53-35
**1MONTH** Screenshot from 2020-08-26 19-53-42

### Trello
https://trello.com/c/2IvZliN9

### CODE REVIEW

**Review by MutegekiHenry — APPROVED** [review]
Awesome work on this @StephenAraka

**Comment by neelxie** [comment]
@StephenAraka 
 I have checked out the PR but I have a few concerns for the x-axis the values disappear could we have a fix for that

Screenshot from 2020-08-26 20-49-20

Screenshot from 2020-08-26 20-49-34

Screenshot from 2020-08-26 20-49-47

**Comment by StephenAraka** [comment]
@neelxie the values do not dissappear. That is how they are... also, if you had read the PR description, I provided context regarding the axis values.

**Review by neelxie — APPROVED** [review]
Good stuff

**Pull request merged**
