### PR TITLE
Fixing project invite stylings

### PR DESCRIPTION
**Pull request by mirembe-mariam**
# Description

- Removed the background under project invite in unregistered users
- Added ellipsis for users whose emails overflow
- Hover functionality on long emails

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Trello Ticket ID

https://trello.com/c/FQDR2UgV

## How Can This Been Tested?

Run this branch locally and checkout the project invite section for unregistered users.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots

Screenshot from 2023-07-12 09-56-37
Screenshot from 2023-07-12 10-02-17

### CODE REVIEW

**Review by khalifan-kfan — COMMENTED** [review]
Nicely done @mirembe-mariam 
Could you please make the truncated long emails end with "..." to show that the is more to it
And also when one hovers over it make the cursor a pointer 
Screenshot 2023-07-12 at 11 19 13
Emails such as,  henrymutegeki@gmail.com  in that screen shot

**Comment by mirembe-mariam** [comment]
i have pushed the changes to the PR @khalifan-kfan

**Review by khalifan-kfan — APPROVED** [review]
LGTM

**Review by neelxie — APPROVED** [review]
LGTM

**Pull request merged**
