### PR TITLE
UX Feedback

### PR DESCRIPTION
**Pull request by neelxie**
# Description
Work on suggested feedback

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Trello Ticket ID
https://trello.com/c/y0TTicMv

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots
Screenshot from 2023-01-12 21-05-27

### CODE REVIEW

**Review by khalifan-kfan — APPROVED** [review]
Looks cool

**Review by rhodinemma — APPROVED** [review]
Thank you for this.

**Review by rhodinemma — APPROVED** [review]
Thank you for this.

**Review by rhodinemma — APPROVED** [review]
Thank you for this.

**Pull request merged**
