### PR TITLE
Creating project tags on the front-end

### PR DESCRIPTION
**Pull request by mosesmulumba**
# Description

This is to illustrate how the project tags will be created on the front-end, someone is able to create a tag and also remove it.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Trello Ticket ID

https://trello.com/c/FKx1RvFI

## How Can This Been Tested?

Fetch the remote branch "ft/project-tags" and visit the project settings and move on to the update modal, there you see an input section for project tags. Add a specific tag to your project, make sure it is not blank. 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots

image

### CODE REVIEW

**Review by khalifan-kfan — DISMISSED** [review]
@mosesmulumba  nice one,

Could  we also have it on project creation

**Comment by khalifan-kfan** [comment]
Screenshot 2024-07-04 at 10 57 07

Could you also  balance the button and in put at this point
Same with the tagged option, atleast aligning every thing in the center

**Comment by khalifan-kfan** [comment]
Also just a suggestion @rhodinemma, @Mubangizi   and @mosesmulumba  could this be a **drop down auto complete input**

**Comment by rhodinemma** [comment]
> Also just a suggestion @rhodinemma, @Mubangizi and @mosesmulumba could this be a **drop down auto complete input**

Good Idea, we could explore how to have them with some sort of auto-complete to save users the hassle of entering tags that we already have in our tags collection, which would also save us the burden of them entering meaningless tags 😅 
and i think the new tags endpoint is searchable, good observation @khalifan-kfan.
Screenshot 2024-07-04 at 11 35 44 AM

Screenshot 2024-07-04 at 11 32 42 AM

**Comment by mosesmulumba** [comment]
Fine then,  I am gonna look through and adjust, so that it can have the
mentioned feedback.

**Review by rhodinemma — APPROVED** [review]
Thanks for working on the feedback @mosesmulumba

**Pull request merged**
