### PR TITLE
billing information

### PR DESCRIPTION
**Pull request by khalifan-kfan**
# Description

This branch is to represent the billing format to the user at the landing page

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Trello Ticket ID

https://trello.com/c/ZiCWPGyD
## How Can This Been Tested?

checkout the branch, click on home page and then pricing to see the billing information page.
Please help identify any spelling issues or  css possible css improvements

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots

image

### CODE REVIEW

**Review by rhodinemma — CHANGES_REQUESTED** [review]
image
 check out those spelling errors, then also why don't we have a pointer on hovering over the pricing details

**Comment by khalifan-kfan** [comment]
thanks, fixed them

**Review by rhodinemma — APPROVED** [review]
nicely done

**Review by neelxie — APPROVED** [review]
Good work

**Pull request merged**
