### PR TITLE
Feat add delete to apps

### PR DESCRIPTION
**Pull request by Mubangizi**
#### what this PR does
- Adds delete option on apps

#### Screen Shots
Screenshot from 2020-04-04 20-34-13

### CODE REVIEW

**Comment by Mubangizi** [comment]
> Your PR says update and delete and yet the update functionality seems to be missing.

Mahn @neelxie Which PR says update? And Update hasnt been implemented because it is not in  the backend. ??? You fine?

**Comment by neelxie** [comment]
> > Your PR says update and delete and yet the update functionality seems to be missing.
> 
> Mahn @neelxie Which PR says update? And Update hasnt been implemented because it is not in the backend. ??? You fine?

it was the branch name sorry

**Comment by Mubangizi** [comment]
> @Mubangizi This is good stuff... Well done. 
> Few things I've noticed:
> 
> * The modal seems to be transparent on my screen (on hover)... Is it just my screen or is it the same for all? Below is a screenshot... If you look closely, you'll realize you can see the background content. Again, this happens on hover.
>   Screenshot from 2020-04-06 10-38-26
> * Lastly, its just a grammar issue for the `Delete` warning. e.g. 'Are You Sure You want to delete matter App?' ... This needs some editing viz:
> 
> 1. Let this be in sentence case (remove unnecessary capital letters)
> 2. remove the App word at the end. (user already knows its an app)
> 3. You could style the name of the app differently (this is just for UX)...
>    So, u end up with the warning looking something like: 'Are you sure you would like to delete `matter`?'

Great, i will work on it

**Comment by Mubangizi** [comment]
I have worked on the feedback @StephenAraka 
this is the new message.
Screenshot from 2020-04-06 15-43-30

**Comment by StephenAraka** [comment]
> I have worked on the feedback @StephenAraka
Thanks for working on this feedback

**Comment by neelxie** [comment]
> Good job @Mubangizi

@Mubangizi Although your PR doesnt show any conflicts, please **REBASE WITH DEVELOP BEFORE YOU MERGE!**

**Pull request merged**
