### PR TITLE
Set up testing

### PR DESCRIPTION
**Pull request by neelxie**
# Description
Set up testing

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Trello Ticket ID
https://trello.com/c/61x1r8Wl

## How Can This Be Tested?
 * Pull this branch locally
 * Run yarn install
 * Run yarn test
PS: Feel free to skip the snapshot files

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by khalifan-kfan — APPROVED** [review]

**Review by e-ian — COMMENTED** [review]
nice work with the setup @neelxie. On pulling the branch and running tests, the component tests run successfully as expected. However, a small nit on some console errors that appear under the button, toggle component test suites.

**Review by e-ian — COMMENTED** [review]
@neelxie is adding a `test_and_report` job in the circleci config part of this PR scope so that the added tests are run on the staging environment. If not, I would recommend it in a subsequent PR.

**Review by e-ian — APPROVED** [review]
LGTM

**Review by rhodinemma — APPROVED** [review]
The tests run successfully.

**Review by khalifan-kfan — APPROVED** [review]

**Pull request merged**
