### PR TITLE
App update

### PR DESCRIPTION
**Pull request by neelxie**
# Description
This adds an application update functionality. Please note env vars can not be added for now

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Trello Ticket ID
https://trello.com/c/B49bYiwJ

## How Can This Be Tested?

Pull this branch locally, navigate to an app and click app settings.
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots
Screenshot from 2021-09-15 07-05-23
Screenshot from 2021-09-15 07-05-33
Screenshot from 2021-09-15 07-05-36

### CODE REVIEW

**Review by MutegekiHenry — APPROVED** [review]
Great work @neelxie

**Review by khalifan-kfan — COMMENTED** [review]
The status of the app is down but this still shows green for the app is live
fail status

**Review by rhodinemma — COMMENTED** [review]
good job but can't these be aligned?
image
@rhodinemma this feedback is design feedback best shared on Figma or on the slack thread about the design, but thank you, if you avail the feedback therein, I will gladly work on it, sir.

**Comment by rhodinemma** [comment]
> good job but can't these be aligned?
> image
> @rhodinemma this feedback is design feedback best shared on Figma or on the slack thread about the design, but thank you, if you avail the feedback therein, I will gladly work on it, sir.

Okay!!

**Review by rhodinemma — APPROVED** [review]
nicely done man.

**Review by khalifan-kfan — APPROVED** [review]

**Pull request merged**
