### PR TITLE
fix sections responsiveness

### PR DESCRIPTION
**Pull request by khalifan-kfan**
# Description

This PR changes the currently braking issues in the frontend's responsiveness

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Trello Ticket ID

https://trello.com/c/lUU4FrvE

## How Can This Been Tested?

Run the branch and checkout out a few user pages on mobile

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots

Screenshot 2023-07-25 at 18 40 22
Screenshot 2023-07-25 at 18 40 38
Screenshot 2023-07-25 at 18 40 57
Screenshot 2023-07-25 at 18 41 11
Screenshot 2023-07-25 at 18 43 42

### CODE REVIEW

**Review by rhodinemma — CHANGES_REQUESTED** [review]
Looks like the createProject form has a `width: 60%` that breaks the form on small screens
image

**Review by ArnaudBand — APPROVED** [review]
### Status: Approved ✔️ ✔️ ✔️
Hi @khalifan-kfan,
#### Congratulations 🎉 Thank you for implementing all the requirements 🙏
review


Please go ahead and merge the branch!
Happy Coding 👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Review by mirembe-mariam — APPROVED** [review]

**Review by mirembe-mariam — APPROVED** [review]

**Review by rhodinemma — APPROVED** [review]
Thank you for this @khalifan-kfan

**Review by neelxie — APPROVED** [review]
LGTM

**Pull request merged**
