### PR TITLE
Fix errors on delete project

### PR DESCRIPTION
**Pull request by StephenAraka**
### what does this do?
- Fixes an error on delete project
- Clear errors in console i.e User Projects page

This is the main error that this PR fixes...
Screenshot from 2020-05-06 14-18-24

Corresponding [Trello ticket](https://trello.com/c/inbWY7Jc)

### CODE REVIEW

**Comment by StephenAraka** [comment]
> resolve conflicts

Screenshot from 2020-05-08 12-44-03

**Comment by MutegekiHenry** [comment]
@StephenAraka some more conflicts to resolve

**Comment by StephenAraka** [comment]
> @StephenAraka some more conflicts to resolve

Damn... must be from the earlier PR... lemme get to it

**Comment by MutegekiHenry** [comment]
> > @StephenAraka some more conflicts to resolve
> 
> @MutegekiHenry Fixed.

cool, lemmi re-check it out

**Pull request merged**
