### PR TITLE
Modify Application Settings

### PR DESCRIPTION
**Pull request by rhodinemma**
# Description

Modifies the application's settings page making it much more informative

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Trello Ticket ID

https://trello.com/c/pmmSeaup

## How Can This Been Tested?

Run this branch locally and visit your application's settings page and review the change.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots

Before
before

After
image

### CODE REVIEW

**Review by neelxie — DISMISSED** [review]
@rhodinemma kindly remove the commented out code as its un-used.

**Comment by rhodinemma** [comment]
> @rhodinemma kindly remove the commented out code as its un-used.

okay.

**Review by neelxie — APPROVED** [review]
Good work with the refactor.

**Review by khalifan-kfan — APPROVED** [review]
looks g

**Review by ttcollins — APPROVED** [review]
Good work @rhodinemma

**Pull request merged**
