### PR TITLE
Search through projects on the admin side

### PR DESCRIPTION
**Pull request by mosesmulumba**
# Description

Admin should be able to search through projects basing on the project names.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Trello Ticket ID

https://trello.com/c/AEO3Ff1a

## How Can This Been Tested?

Pull the upstream branch and run it locally on your end.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots
Search through image
searchThrough

#Before
datefilter_projectlogs

#after
afterstyles

### CODE REVIEW

**Review by neelxie — APPROVED** [review]
LGTM

**Review by khalifan-kfan — CHANGES_REQUESTED** [review]
@mosesmulumba  Due to pagination, this feature is much better implemented through the endpoint.

In this current state, if i search for a project on page 8 while am on page 1, I will not have results

**Review by rhodinemma — APPROVED** [review]
Thank you for this @mosesmulumba

**Review by mirembe-mariam — DISMISSED** [review]

**Review by neelxie — APPROVED** [review]
LGTM

**Pull request merged**
