### PR TITLE
Adding time selector to spending graph

### PR DESCRIPTION
**Pull request by khalifan-kfan**
# Description

This PR adds the choice for a user creating to imput the time for the range of metrics they would like on the amount spent per month on their projects. 
It also refactors some code to components 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Trello Ticket ID

https://trello.com/c/zIDe2wIn

## How Can This Been Tested?

Pull the branch and check the billing page out on the projects  

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots

ti m

### CODE REVIEW

**Review by neelxie — APPROVED** [review]
Good stuff on this

**Review by rhodinemma — APPROVED** [review]
Working fine.

**Review by e-ian — APPROVED** [review]

**Review by Mubangizi — CHANGES_REQUESTED** [review]
Hey @rhodinemma, great work.
Just a little feedback on the custom model. I think it would be better if you aligned the `to`, `from` and `submit button` vertically.
instead of
```
From: [..........]     To: [..........]
       [      submit    ] 
```
to something like;
```
    From: [.........]
    To: [...........]
    [    submit     ]
```

**Comment by rhodinemma** [comment]
> Hey @rhodinemma, great work. Just a little feedback on the custom model. I think it would be better if you aligned the `to`, `from` and `submit button` vertically. instead of
> 
> ```
> From: [..........]     To: [..........]
>        [      submit    ] 
> ```
> 
> to something like;
> 
> ```
>     From: [.........]
>     To: [...........]
>     [    submit     ]
> ```

CC: @khalifan-kfan

**Comment by khalifan-kfan** [comment]
On it

**Review by neelxie — APPROVED** [review]
Good work @khalifan-kfan

**Comment by e-ian** [comment]
@khalifan-kfan please update the screenshot in the PR

**Comment by khalifan-kfan** [comment]
sure
image

**Review by Mubangizi — APPROVED** [review]
Great work @khalifan-kfan, just a few things that you can also look at
- Removing the drop shadow don't the date inputs
- Also align the `submit` button to the same width as inputs.
- Then try reducing the padding around the inputs and the model, I feel like there is a lot of space.

You may or may not do the above, there just opinions

**Comment by khalifan-kfan** [comment]
Please re-review, I have changed the month selector from <input type="month" ..... after fiinding out it doesnt render in some browsers like firefox. refactored it to use a component that already exists in the codebase
image

**Review by neelxie — APPROVED** [review]
LGTM

**Review by rhodinemma — APPROVED** [review]

**Pull request merged**
