### PR TITLE
 Show user apps list

### PR DESCRIPTION
**Pull request by Mubangizi**
#### What this PR does?
Creates an Apps Page, Asks for input on how Apps interface should look like?

#### How can it be accessed?
Click on a project to see its apps

#### Further information?
- Am currently using dummy data,  that's why log in isn't required.
- Main Focus is on the UI for now

#### Screenshots

Screenshot from 2020-03-25 02-28-11

#### New Apps List page
Screenshot from 2020-03-26 19-36-15

#### No apps Page
Screenshot from 2020-03-26 19-37-06

#### Note.
this PR changes projects route from `/:userID/projects` to `/users/:userID/projects`

### CODE REVIEW

**Comment by StephenAraka** [comment]
Where is the help needed?

**Comment by Mubangizi** [comment]
> Where is the help needed?

It was about Whats needed on the Apps card infor to display, like Are you fine with that since there no mockapps

**Comment by Mubangizi** [comment]
> Hey @Mubangizi, this is brilliant work!
> The design looks sleek and detailed. I approve of it.
> Seen a few warnings but I bet these will be cleared coz its still WIP. Also, I realize the data is static for now.
> Are the apps implemented in the backend?

No for now i was having difficulty with accessing projects page, so i decided to just do a static page. Then if approved i will plug everything in.

**Comment by MutegekiHenry** [comment]
> > Where is the help needed?
> 
> It was about Whats needed on the Apps card, infor to display, like Are you fine with that?, should we add some stuff. since there no mockapps

Great work @Mubangizi On the Design, i think that can work for now and can always iterate when the figma designs are out and anything changes, On the App info, i think we agreed in the last design meeting that all we need is the status and link to app which clearly you have. My only problem is that you missed to put the Back button that is meant to take the user back to the projects page, otherwise all is well.

**Comment by Mubangizi** [comment]
> > > Where is the help needed?
> > 
> > 
> > It was about Whats needed on the Apps card, infor to display, like Are you fine with that?, should we add some stuff. since there no mockapps
> 
> Great work @Mubangizi On the Design, i think that can work for now and can always iterate when the figma designs are out and anything changes, On the App info, i think we agreed in the last design meeting that all we need is the status and link to app which clearly you have. My only problem is that you missed to put the Back button that is meant to take the user back to the projects page, otherwise all is well.

Yeah i will add the button

**Comment by StephenAraka** [comment]
@Mubangizi , why does this change the user projects route?

**Comment by Mubangizi** [comment]
> @Mubangizi , why does this change the user projects route?

We are supposed to implement with the RESTful API design, which requires us to add the element name before you put its id
You can refer to this link for more information
 https://hackernoon.com/restful-api-designing-guidelines-the-best-practices-60e1d954e7c9

**Comment by StephenAraka** [comment]
> > @Mubangizi , why does this change the user projects route?
> 
> We are supposed to implement with the RESTful API design, which requires us to add the element name before you put its id
> You can refer to this link for more information
> https://hackernoon.com/restful-api-designing-guidelines-the-best-practices-60e1d954e7c9

Meaning I'll have to change this for the login as we... coz they are currently redirecting to /:userid/projects

**Comment by StephenAraka** [comment]
Should we approve or are you still WIP?

**Comment by Mubangizi** [comment]
> > > @Mubangizi , why does this change the user projects route?
> > 
> > 
> > We are supposed to implement with the RESTful API design, which requires us to add the element name before you put its id
> > You can refer to this link for more information
> > https://hackernoon.com/restful-api-designing-guidelines-the-best-practices-60e1d954e7c9
> 
> Meaning I'll have to change this for the login as we... coz they are currently redirecting to /:userid/projects

No need I changed it too

**Comment by Mubangizi** [comment]
> Should we approve or are you still WIP?

What is WIP?

**Comment by StephenAraka** [comment]
> > Should we approve or are you still WIP?
> 
> What is WIP?

work in progress... I see like ur still pushing code
!

**Comment by StephenAraka** [comment]
> > > > @Mubangizi , why does this change the user projects route?
> > > 
> > > 
> > > We are supposed to implement with the RESTful API design, which requires us to add the element name before you put its id
> > > You can refer to this link for more information
> > > https://hackernoon.com/restful-api-designing-guidelines-the-best-practices-60e1d954e7c9
> > 
> > 
> > Meaning I'll have to change this for the login as we... coz they are currently redirecting to /:userid/projects
> 
> No need I changed it too

aaah! thanks man!

**Comment by Mubangizi** [comment]
> > > @Mubangizi , why does this change the user projects route?
> > 
> > 
> > We are supposed to implement with the RESTful API design, which requires us to add the element name before you put its id
> > You can refer to this link for more information
> > https://hackernoon.com/restful-api-designing-guidelines-the-best-practices-60e1d954e7c9
> 
> Meaning I'll have to change this for the login as we... coz they are currently redirecting to /:userid/projects

Am done

**Pull request merged**
